select 
date,
CAMPAIGN_name__FACEBOOK_ADS as acq_channel_level_2,
sum(AMOUNT_SPENT__FACEBOOK_ADS) as amount_spent
from "SHARED_FUNNEL_SUMUP__LM3JD3KWKTSKJUJGEZZ"."FUNNEL__LM3JD3KWKTSKJUJGEZZ"."PARTNERS_FACEBOOK_CAMPAIGNS_CHILE"
where date = '_start_date'
group by 1,2